REDIRECT_URI = 'YOUR_REDIRECT_URL'
CONSUMER_ID = 'YOUR_CONSUMER_ID'
ACCOUNT_NUMBER = 'YOUR_ACCOUNT_NUMBER_OR_USERNAME' # FOR TD DEVELOPER ACCOUNT
TD_ACCOUNT = 'YOUR_ACCOUNT_NUMBER_FOR_TRADING'
ACCOUNT_PASSWORD = 'YOUR_PASSWORD'
